# role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argo-cd
  name: secret-manager
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "delete"]
---
# rolebinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-manager-binding
  namespace: argo-cd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-manager
subjects:
- kind: ServiceAccount
  name: default
  namespace: argo-cd
---
# Job to delete initial ArgoCD admin secret
apiVersion: batch/v1
kind: Job
metadata:
  name: delete-initial-secret-job
  namespace: argo-cd
spec:
  template:
    spec:
      containers:
      - name: delete-secret
        image: bitnami/kubectl:latest
        command:
          - "kubectl"
          - "delete"
          - "secret"
          - "-n"
          - "argo-cd"
          - "argocd-initial-admin-secret"
      restartPolicy: OnFailure
