---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minikube
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/aleksander-raskin/argocd-sandbox.git
    targetRevision: HEAD
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/aleksander-raskin/argocd-sandbox.git
    targetRevision: HEAD
    path: external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated: {}
