apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 25.13.0
    chart: prometheus
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
