apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.13
    chart: external-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
